checks:
    php: true
build:
    environment:
        php:
            version: 7.0
            ini:
                'date.timezone': 'Paris/Europe'
    tests:
        override:
            -
                command: 'phpunit --coverage-clover coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'php-clover'