imports:
    - { resource: parameters.yml }
    - { resource: rabbitmq.yml }
    - { resource: doctrine.yml }
    - { resource: elasticsearch.yml }
    - { resource: mapping.yml }

framework:
    secret:          "%secret%"
    csrf_protection: ~
    validation:      { enable_annotations: true }
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  ~
    fragments:       ~
